---
driver:
  name: docker
  use_sudo: false
  privileged: true

verifier:
  name: inspec
  format: doc

provisioner:
  name: salt_solo
  log_level: debug
  require_chef: false
  formula: vault

platforms:
  - name: ubuntu-16.04
    driver_config:
      provision_command:
        - apt-get update && apt-get install -y locales && locale-gen en_US.UTF-8
      run_command: /sbin/init
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
  - name: amazonlinux
    driver_config:
      image: amazonlinux:latest
      platform: rhel
      run_command: /sbin/init

suites:
  - name: dev_server_systemd
    excludes:
      - amazonlinux
    provisioner:
      state_top:
        base:
          '*':
            - vault
            - vault.server
      pillars:
        top.sls:
          base:
            '*':
              - vault
        vault.sls:
          vault:
            service:
              type: systemd
            server:
              max_lease_ttl: 24h
              default_lease_ttl: 24h
              listener:
                - tcp:
                    address: "0.0.0.0:8200"
                    tls_disable: true
              storage:
                file: 
                  path: "/tmp/vault"

  - name: dev_server_upstart_s3
    includes:
      - amazonlinux
    provisioner:
      state_top:
        base:
          '*':
            - vault
            - vault.server
      pillars:
        top.sls:
          base:
            '*':
              - vault
        vault.sls:
          vault:
            service:
              type: upstart
            server:
              max_lease_ttl: 24h
              default_lease_ttl: 24h
              listener:
                - tcp:
                    address: "0.0.0.0:8200"
                    tls_disable: true
              storage:
                s3: 
                  bucket: "vault-formula-bucket"
